import logging

from django.conf import settings as django_settings
from django.shortcuts import render
from django.views.generic import View

from accounts.views import GlobalVars
import config

logger = logging.getLogger('app')

TOOL_LIMITS = django_settings.TOOL_LIMITS.get('paraphraser', {})
FREE_WORD_LIMIT = TOOL_LIMITS.get('free_words', 500)
FREE_MODES = TOOL_LIMITS.get('free_modes', ['standard', 'fluency'])
ALL_MODES = [
    'standard', 'fluency', 'formal', 'academic', 'simple',
    'creative', 'expand', 'shorten', 'custom', 'humanizer',
]


# --- SEO page content definitions ---

SEO_PAGES = {
    'rewording-tool': {
        'h1': 'Free Rewording Tool',
        'subtitle': 'Instantly reword any text while keeping its original meaning. Our AI-powered rewording tool helps you express ideas in fresh, unique ways.',
        'meta_title': 'Free Rewording Tool Online',
        'meta_description': 'Reword sentences, paragraphs, and essays instantly with our free AI rewording tool. Improve clarity, avoid plagiarism, and find better ways to express your ideas.',
        'features': [
            {'title': 'Smart Rewording', 'text': 'Our AI understands context and meaning, not just swapping synonyms. Get natural, fluent rewording every time.'},
            {'title': 'Multiple Styles', 'text': 'Choose from 10 rewording modes: standard, fluency, formal, academic, simple, creative, and more.'},
            {'title': 'Preserve Meaning', 'text': 'Advanced AI ensures your reworded text keeps the same meaning while using different words and structures.'},
        ],
        'faqs': [
            {'q': 'What is a rewording tool?', 'a': 'A rewording tool takes your original text and rephrases it using different words and sentence structures while preserving the original meaning. It helps you avoid repetition and express ideas in new ways.'},
            {'q': 'Is this rewording tool free?', 'a': 'Yes, our rewording tool is completely free for texts up to 500 words. Premium users can reword unlimited text with access to all 10 modes.'},
            {'q': 'Will rewording my text count as plagiarism?', 'a': 'Rewording tool output is original text generated by AI. However, always ensure the ideas are properly attributed if they come from a source. Use our plagiarism checker to verify.'},
        ],
    },
    'sentence-rewriter': {
        'h1': 'Free Sentence Rewriter',
        'subtitle': 'Rewrite individual sentences with perfect grammar and natural flow. Transform awkward sentences into polished, professional writing.',
        'meta_title': 'Free Sentence Rewriter Online',
        'meta_description': 'Rewrite sentences instantly with our free AI sentence rewriter. Improve clarity, grammar, and readability while keeping your original meaning.',
        'features': [
            {'title': 'Sentence-Level Precision', 'text': 'Optimized for rewriting individual sentences with maximum accuracy and natural phrasing.'},
            {'title': 'Grammar Perfection', 'text': 'Every rewritten sentence is grammatically correct and reads naturally.'},
            {'title': 'Tone Control', 'text': 'Rewrite sentences in formal, casual, academic, or creative tones to match your audience.'},
        ],
        'faqs': [
            {'q': 'How does the sentence rewriter work?', 'a': 'Our AI analyzes your sentence structure, meaning, and context, then generates alternative versions that express the same idea differently while maintaining grammatical accuracy.'},
            {'q': 'Can I rewrite multiple sentences at once?', 'a': 'Yes, while optimized for individual sentences, you can paste paragraphs and our tool will rewrite each sentence while maintaining overall coherence.'},
            {'q': 'How is this different from a paraphrasing tool?', 'a': 'Our sentence rewriter is specifically tuned for sentence-level rewrites with higher precision for short text, while a paraphrasing tool is designed for longer passages.'},
        ],
    },
    'paragraph-rewriter': {
        'h1': 'Free Paragraph Rewriter',
        'subtitle': 'Rewrite entire paragraphs with improved flow, clarity, and coherence. Perfect for essays, articles, and professional documents.',
        'meta_title': 'Free Paragraph Rewriter Online',
        'meta_description': 'Rewrite paragraphs instantly with our free AI paragraph rewriter. Improve writing quality, avoid plagiarism, and maintain your original meaning.',
        'features': [
            {'title': 'Paragraph-Level Coherence', 'text': 'Maintains logical flow and transitions between sentences throughout the rewritten paragraph.'},
            {'title': 'Improved Readability', 'text': 'Automatically enhances sentence variety, word choice, and overall readability scores.'},
            {'title': 'Academic Quality', 'text': 'Perfect for rewriting academic paragraphs with formal vocabulary and proper structure.'},
        ],
        'faqs': [
            {'q': 'How long can my paragraph be?', 'a': 'Free users can rewrite paragraphs up to 500 words. Premium users have no word limit.'},
            {'q': 'Does it keep my paragraph structure?', 'a': 'The tool preserves your paragraph\'s logical structure and argument flow while rephrasing individual sentences and improving transitions.'},
            {'q': 'Can I use this for academic papers?', 'a': 'Yes, select the "Academic" mode for scholarly vocabulary and formal structure appropriate for research papers and essays.'},
        ],
    },
    'essay-rewriter': {
        'h1': 'Free Essay Rewriter',
        'subtitle': 'Rewrite entire essays while maintaining argument structure, thesis, and supporting evidence. Ideal for students and academic writers.',
        'meta_title': 'Free Essay Rewriter Online',
        'meta_description': 'Rewrite essays with our free AI essay rewriter. Maintain your argument, improve vocabulary, and create original content for academic success.',
        'features': [
            {'title': 'Argument Preservation', 'text': 'Maintains your essay\'s thesis, supporting arguments, and logical structure throughout the rewrite.'},
            {'title': 'Academic Vocabulary', 'text': 'Upgrades vocabulary to academic standards while keeping your writing accessible and clear.'},
            {'title': 'Citation Awareness', 'text': 'Recognizes and preserves in-text citations and references during the rewriting process.'},
        ],
        'faqs': [
            {'q': 'Will the rewriter change my essay\'s thesis?', 'a': 'No, our AI is trained to preserve your central argument and thesis statement while rephrasing supporting content for originality.'},
            {'q': 'Is it considered cheating to use an essay rewriter?', 'a': 'Using a rewriter as a learning tool to improve your writing is acceptable. However, always follow your institution\'s academic integrity policies.'},
            {'q': 'Can it handle long essays?', 'a': 'Premium users can rewrite essays of any length. Free users are limited to 500 words per submission.'},
        ],
    },
    'article-rewriter': {
        'h1': 'Free Article Rewriter',
        'subtitle': 'Rewrite articles for blogs, news, and content marketing. Generate unique versions while preserving facts, tone, and SEO value.',
        'meta_title': 'Free Article Rewriter Online',
        'meta_description': 'Rewrite articles instantly with our free AI article rewriter. Create unique content for SEO, blogs, and marketing while preserving facts and quality.',
        'features': [
            {'title': 'SEO-Friendly Output', 'text': 'Rewrites preserve keyword density and search-engine-friendly structure for maximum SEO value.'},
            {'title': 'Factual Accuracy', 'text': 'Preserves all facts, statistics, and data points from the original article during rewriting.'},
            {'title': 'Tone Matching', 'text': 'Maintains your brand voice and article tone across the entire rewritten piece.'},
        ],
        'faqs': [
            {'q': 'Will rewriting hurt my SEO?', 'a': 'Our article rewriter preserves important keywords and phrases while creating unique content, which can actually improve SEO by providing original text.'},
            {'q': 'Can I rewrite articles from other sources?', 'a': 'While the tool can rewrite any text, always ensure you have the right to use the original content and provide proper attribution where required.'},
            {'q': 'Does it work for news articles?', 'a': 'Yes, the tool is excellent for rewriting news content while preserving all factual information, dates, names, and quotes.'},
        ],
    },
    'text-rewriter': {
        'h1': 'Free Text Rewriter',
        'subtitle': 'Rewrite any text quickly and easily. Whether it is a few words or entire documents, get unique, readable output in seconds.',
        'meta_title': 'Free Text Rewriter Online',
        'meta_description': 'Rewrite any text instantly with our free AI text rewriter. Transform your writing with fresh vocabulary and improved structure.',
        'features': [
            {'title': 'Universal Text Support', 'text': 'Works with any type of text: emails, reports, social media posts, academic papers, and more.'},
            {'title': 'Instant Results', 'text': 'Get rewritten text in seconds, not minutes. Our AI processes text faster than any manual rewrite.'},
            {'title': 'Multiple Outputs', 'text': 'Generate different versions of the same text to find the perfect fit for your needs.'},
        ],
        'faqs': [
            {'q': 'What types of text can I rewrite?', 'a': 'You can rewrite any English text including emails, reports, essays, articles, social media posts, product descriptions, and more.'},
            {'q': 'How many times can I rewrite the same text?', 'a': 'You can rewrite the same text as many times as you like. Each rewrite generates a unique version.'},
            {'q': 'Is the output unique?', 'a': 'Yes, each rewrite produces original text. We recommend using our plagiarism checker to verify uniqueness for important documents.'},
        ],
    },
    'spell-checker': {
        'h1': 'Free Online Spell Checker',
        'subtitle': 'Check and fix spelling errors instantly. Our AI-powered spell checker catches mistakes that basic tools miss.',
        'meta_title': 'Free Online Spell Checker',
        'meta_description': 'Check spelling online for free. Our AI spell checker catches typos, misspellings, and commonly confused words. Works with any text.',
        'features': [
            {'title': 'Contextual Spelling', 'text': 'Catches spelling errors based on context, including commonly confused words like "their/there/they\'re".'},
            {'title': 'Multi-Language Support', 'text': 'Check spelling in multiple languages with language-specific dictionaries and rules.'},
            {'title': 'One-Click Fixes', 'text': 'Click on any highlighted error to see suggestions and apply corrections instantly.'},
        ],
        'faqs': [
            {'q': 'How accurate is the spell checker?', 'a': 'Our AI-powered spell checker catches contextual errors that basic spell checkers miss, with over 99% accuracy on standard English text.'},
            {'q': 'Does it check grammar too?', 'a': 'While primarily a spell checker, our tool also catches basic grammatical errors. For comprehensive grammar checking, try our dedicated Grammar Checker tool.'},
            {'q': 'Can I check spelling in other languages?', 'a': 'Yes, our spell checker supports multiple languages. Select your language from the dropdown to get language-specific spelling corrections.'},
        ],
    },
    'punctuation-checker': {
        'h1': 'Free Punctuation Checker',
        'subtitle': 'Fix punctuation errors automatically. Commas, periods, semicolons, apostrophes, and more -- all checked by AI.',
        'meta_title': 'Free Punctuation Checker Online',
        'meta_description': 'Check and fix punctuation errors online for free. Our AI punctuation checker handles commas, apostrophes, semicolons, and all punctuation marks.',
        'features': [
            {'title': 'Complete Punctuation Check', 'text': 'Checks all punctuation marks: commas, periods, semicolons, colons, apostrophes, quotation marks, and more.'},
            {'title': 'Comma Placement', 'text': 'Specialized in comma rules including Oxford commas, introductory phrases, and compound sentences.'},
            {'title': 'Style Consistency', 'text': 'Ensures consistent punctuation style throughout your document.'},
        ],
        'faqs': [
            {'q': 'What punctuation errors does it catch?', 'a': 'Our tool checks for missing commas, incorrect apostrophes, wrong quotation marks, missing periods, semicolon misuse, and all other punctuation errors.'},
            {'q': 'Does it follow American or British punctuation rules?', 'a': 'By default, it follows American English punctuation rules. You can switch to British English in the settings.'},
            {'q': 'Can it fix run-on sentences?', 'a': 'Yes, our tool identifies run-on sentences and suggests proper punctuation to break them into clear, readable sentences.'},
        ],
    },
    'essay-checker': {
        'h1': 'Free Essay Checker',
        'subtitle': 'Check your essays for grammar, spelling, punctuation, and style errors. Get a comprehensive writing quality score.',
        'meta_title': 'Free Essay Checker Online',
        'meta_description': 'Check your essay for grammar, spelling, and style errors. Get a writing quality score and actionable suggestions to improve your writing.',
        'features': [
            {'title': 'Comprehensive Analysis', 'text': 'Checks grammar, spelling, punctuation, style, word choice, and sentence structure in one pass.'},
            {'title': 'Writing Score', 'text': 'Get a 0-100 writing quality score with specific feedback on how to improve.'},
            {'title': 'Academic Standards', 'text': 'Evaluates essays against academic writing standards including formality, clarity, and argumentation.'},
        ],
        'faqs': [
            {'q': 'What does the writing score mean?', 'a': 'The writing score (0-100) evaluates overall quality including grammar accuracy, vocabulary diversity, sentence structure variety, and coherence. Scores above 80 indicate strong writing.'},
            {'q': 'Can it check different types of essays?', 'a': 'Yes, our essay checker works with argumentative, expository, narrative, descriptive, and all other essay types.'},
            {'q': 'Will it help improve my essay?', 'a': 'Yes, beyond error detection, the tool provides specific suggestions for improving clarity, flow, word choice, and overall writing quality.'},
        ],
    },
    'online-proofreader': {
        'h1': 'Free Online Proofreader',
        'subtitle': 'Proofread your text professionally. Catch every error in grammar, spelling, punctuation, and style before you publish.',
        'meta_title': 'Free Online Proofreader',
        'meta_description': 'Proofread your text online for free. Our AI proofreader catches grammar, spelling, punctuation, and style errors with professional accuracy.',
        'features': [
            {'title': 'Professional-Grade', 'text': 'Catches errors that even experienced human proofreaders might miss, with AI-powered contextual understanding.'},
            {'title': 'Style Suggestions', 'text': 'Goes beyond error correction to suggest improvements for clarity, conciseness, and readability.'},
            {'title': 'Track Changes', 'text': 'See all suggested changes clearly highlighted so you can accept or reject each one individually.'},
        ],
        'faqs': [
            {'q': 'How is this different from a spell checker?', 'a': 'A proofreader checks much more than spelling: it reviews grammar, punctuation, word choice, sentence structure, consistency, and style -- providing a comprehensive review of your writing.'},
            {'q': 'Can I use it for professional documents?', 'a': 'Absolutely. Our proofreader is used for business reports, marketing copy, academic papers, legal documents, and all professional writing.'},
            {'q': 'Does it support long documents?', 'a': 'Free users can proofread up to 500 words per check. Premium users can proofread documents of any length.'},
        ],
    },
}


class SEOLandingPage(View):
    """
    Generic SEO landing page view.
    Renders the paraphraser tool with SEO-specific content surrounding it.
    """
    page_key = None

    def get(self, request):
        g = GlobalVars.get_globals(request)
        page_data = SEO_PAGES.get(self.page_key, {})

        if not page_data:
            return render(request, '404.html', {'g': g}, status=404)

        is_premium = request.user.is_authenticated and request.user.is_plan_active

        return render(request, 'seo/landing.html', {
            'title': f'{page_data["meta_title"]} | {config.PROJECT_NAME}',
            'description': page_data['meta_description'],
            'page': self.page_key,
            'g': g,
            'seo': page_data,
            'is_premium': is_premium,
            'free_word_limit': FREE_WORD_LIMIT,
            'free_modes': FREE_MODES,
            'all_modes': ALL_MODES,
        })


class RewordingToolPage(SEOLandingPage):
    page_key = 'rewording-tool'


class SentenceRewriterPage(SEOLandingPage):
    page_key = 'sentence-rewriter'


class ParagraphRewriterPage(SEOLandingPage):
    page_key = 'paragraph-rewriter'


class EssayRewriterPage(SEOLandingPage):
    page_key = 'essay-rewriter'


class ArticleRewriterPage(SEOLandingPage):
    page_key = 'article-rewriter'


class TextRewriterPage(SEOLandingPage):
    page_key = 'text-rewriter'


class SpellCheckerPage(SEOLandingPage):
    page_key = 'spell-checker'


class PunctuationCheckerPage(SEOLandingPage):
    page_key = 'punctuation-checker'


class EssayCheckerPage(SEOLandingPage):
    page_key = 'essay-checker'


class OnlineProofreaderPage(SEOLandingPage):
    page_key = 'online-proofreader'
