from django.urls import path

from media_tools.views import (
    MediaToolsIndex, ImageToolsIndex, ImageConverterPage, BackgroundRemoverPage,
    AIImageGeneratorPage, QRCodePage, VoiceGeneratorPage,
    TranscriptionPage, LogoGeneratorPage, CharacterGeneratorPage,
    WordCloudPage, BannerGeneratorPage, PresentationMakerPage,
    AIImageToolPage, AIImageToolAPI,
    ImageConvertAPI, BackgroundRemoveAPI, QRCodeAPI,
    VoiceGenerateAPI, AIImagePromptAPI,
    TranscribeAPI, LogoGenerateAPI, CharacterGenerateAPI,
    WordCloudAPI, BannerGenerateAPI, PresentationGenerateAPI,
)

urlpatterns = [
    # Page views
    path('image-tools/', ImageToolsIndex.as_view(), name='image_tools_index'),
    path('tools/ai-image-generator/', AIImageGeneratorPage.as_view(), name='ai_image_generator'),
    path('converter-tools/', ImageConverterPage.as_view(), name='image_converter'),
    path('background-remover/', BackgroundRemoverPage.as_view(), name='background_remover'),
    path('tools/qr-code-generator/', QRCodePage.as_view(), name='qr_code_generator'),
    path('tools/ai-voice-generator/', VoiceGeneratorPage.as_view(), name='voice_generator'),
    path('tools/transcription/', TranscriptionPage.as_view(), name='transcription'),
    path('speech-to-text/', TranscriptionPage.as_view(), name='speech_to_text'),
    path('tools/logo-generator/', LogoGeneratorPage.as_view(), name='logo_generator'),
    path('tools/character-generator/', CharacterGeneratorPage.as_view(), name='character_generator'),
    path('tools/word-cloud/', WordCloudPage.as_view(), name='word_cloud'),
    path('tools/banner-generator/', BannerGeneratorPage.as_view(), name='banner_generator'),
    path('tools/presentation-maker/', PresentationMakerPage.as_view(), name='presentation_maker'),
    path('media-tools/', MediaToolsIndex.as_view(), name='media_tools_index'),

    # AI Image Tool pages (27 tools)
    path('tools/art-generator/', AIImageToolPage.as_view(tool_key='art-generator'), name='art_generator'),
    path('tools/poster-generator/', AIImageToolPage.as_view(tool_key='poster-generator'), name='poster_generator'),
    path('tools/flyer-generator/', AIImageToolPage.as_view(tool_key='flyer-generator'), name='flyer_generator'),
    path('tools/thumbnail-generator/', AIImageToolPage.as_view(tool_key='thumbnail-generator'), name='thumbnail_generator'),
    path('tools/youtube-thumbnail/', AIImageToolPage.as_view(tool_key='youtube-thumbnail'), name='youtube_thumbnail'),
    path('tools/icon-generator/', AIImageToolPage.as_view(tool_key='icon-generator'), name='icon_generator'),
    path('tools/mockup-generator/', AIImageToolPage.as_view(tool_key='mockup-generator'), name='mockup_generator'),
    path('tools/illustration-generator/', AIImageToolPage.as_view(tool_key='illustration-generator'), name='illustration_generator'),
    path('tools/design-generator/', AIImageToolPage.as_view(tool_key='design-generator'), name='design_generator'),
    path('tools/product-image-generator/', AIImageToolPage.as_view(tool_key='product-image-generator'), name='product_image_generator'),
    path('tools/avatar-generator/', AIImageToolPage.as_view(tool_key='avatar-generator'), name='avatar_generator'),
    path('tools/portrait-generator/', AIImageToolPage.as_view(tool_key='portrait-generator'), name='portrait_generator'),
    path('tools/wallpaper-generator/', AIImageToolPage.as_view(tool_key='wallpaper-generator'), name='wallpaper_generator'),
    path('tools/background-generator/', AIImageToolPage.as_view(tool_key='background-generator'), name='background_generator'),
    path('tools/infographic-generator/', AIImageToolPage.as_view(tool_key='infographic-generator'), name='infographic_generator'),
    path('tools/book-cover-generator/', AIImageToolPage.as_view(tool_key='book-cover-generator'), name='book_cover_generator'),
    path('tools/packaging-design-generator/', AIImageToolPage.as_view(tool_key='packaging-design-generator'), name='packaging_design_generator'),
    path('tools/album-cover-generator/', AIImageToolPage.as_view(tool_key='album-cover-generator'), name='album_cover_generator'),
    path('tools/tattoo-generator/', AIImageToolPage.as_view(tool_key='tattoo-generator'), name='tattoo_generator'),
    path('tools/pixel-art-generator/', AIImageToolPage.as_view(tool_key='pixel-art-generator'), name='pixel_art_generator'),
    path('tools/pattern-generator/', AIImageToolPage.as_view(tool_key='pattern-generator'), name='pattern_generator'),
    path('tools/3d-model-generator/', AIImageToolPage.as_view(tool_key='3d-model-generator'), name='3d_model_generator'),
    path('tools/storyboard-generator/', AIImageToolPage.as_view(tool_key='storyboard-generator'), name='storyboard_generator'),
    path('tools/fantasy-map-generator/', AIImageToolPage.as_view(tool_key='fantasy-map-generator'), name='fantasy_map_generator'),
    path('tools/cartoon-generator/', AIImageToolPage.as_view(tool_key='cartoon-generator'), name='cartoon_generator'),
    path('tools/comic-generator/', AIImageToolPage.as_view(tool_key='comic-generator'), name='comic_generator'),
    path('tools/action-figure-generator/', AIImageToolPage.as_view(tool_key='action-figure-generator'), name='action_figure_generator'),

    # API endpoints
    path('api/media/convert-image/', ImageConvertAPI.as_view(), name='image_convert_api'),
    path('api/media/remove-bg/', BackgroundRemoveAPI.as_view(), name='bg_remove_api'),
    path('api/media/qr-code/', QRCodeAPI.as_view(), name='qr_code_api'),
    path('api/media/text-to-speech/', VoiceGenerateAPI.as_view(), name='voice_api'),
    path('api/media/ai-image/', AIImagePromptAPI.as_view(), name='ai_image_api'),
    path('api/media/transcribe/', TranscribeAPI.as_view(), name='transcribe_api'),
    path('api/media/logo/', LogoGenerateAPI.as_view(), name='logo_api'),
    path('api/media/character/', CharacterGenerateAPI.as_view(), name='character_api'),
    path('api/media/word-cloud/', WordCloudAPI.as_view(), name='word_cloud_api'),
    path('api/media/banner/', BannerGenerateAPI.as_view(), name='banner_api'),
    path('api/media/presentation/', PresentationGenerateAPI.as_view(), name='presentation_api'),
    path('api/media/image-tool/', AIImageToolAPI.as_view(), name='image_tool_api'),
]
